name: rp
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    dns:
      - "8.8.8.8"
    container_name: rp-node
    working_dir: /var/www/html
# set manually if needed
#    platform: linux/arm64/v8
    stdin_open: true
    tty: true
    volumes:
      - "./:/var/www/html"
    ports:
      - "3080:3080"
    entrypoint: ["/var/www/html/entrypoint.sh"]
