name: rp
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    dns:
      - "8.8.8.8"
    container_name: rp-node
    working_dir: /var/www/html
    platform: linux/arm64/v8
    stdin_open: true
    tty: true
    volumes:
      - "./:/var/www/html"
    ports:
      - "9050:9050"
      - "3080:3080"
      - "8080:8080"
    networks:
      rpnet:
        ipv4_address: 192.168.211.20

networks:
  rpnet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.211.0/24
